[package]
name = "network"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
log4rs = "*"
clap = "3.0.0-beta.2"
git-version = "*"
p2p_simple = { git = "https://github.com/cita-cloud/p2p_simple.git", branch = "master" }
toml = "*"
serde = "*"
serde_derive = "*"
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
